#lang scheme
(define (pair x y)
  (cons x y)
  )
(define (first pair)
  (car pair)
  )
(define (second pair)
  (cdr pair)
  )
(define (pair2 x y)
  (define (save pos)
    (cond ((= 0 pos) x)
          ((= 1 pos) y)
          (else (error "invalid position"))
          )
    )
  save
  )
(define (first2 pair)
  (pair 0)
  )
(define (second2 pair)
  (pair 1)
  )
(define x (pair 1 2))
(first x)
(second x)
(define xx (pair2 3 4))
(first2 xx)
(second2 xx)
